/* The text sweep's record (Oct 2, 2026): every user-visible sentence,
   helper line, caption or "A · B" meta line that was cut or replaced, by
   surface, so Brandon can scan the whole pass on /dev/copy-review.html.
   `after` is what stands in its place: a visual ("photo chips", "lamp",
   "PayoutLadder") in brackets, new words in quotes, or null when nothing
   replaces it. Dev-only; never imported by the app. */
export const CUTS = [
  { surface:"Home", file:"src/features/home/GuestHome.jsx", before:"{role detail} (crew card: \"Calls rules and settles close plays.\" etc.)", after:null },
  { surface:"Home", file:"src/features/home/GuestHome.jsx", before:"{round} · Your team", after:"\"Your team\"" },
  { surface:"Home", file:"src/features/home/GuestHome.jsx", before:"{status} · {round}", after:"\"{status}\"" },
  { surface:"Home", file:"src/features/home/GuestHome.jsx", before:"Your role · {role}", after:"\"{role}\"" },
  { surface:"Home", file:"src/features/home/GuestHome.jsx", before:"You won · with {partner}", after:"\"You won with {partner}\"" },
  { surface:"Home", file:"src/features/home/GuestHome.jsx", before:"You finished {place} · {chips}", after:"\"You finished {place}\" (chips are on the board)" },
  { surface:"Home", file:"src/features/home/homeModel.js", before:"Won +{chips} · {event}", after:"\"{event}: Won +{chips}\"" },
  { surface:"Home", file:"src/features/home/guestUpdates.js", before:"Since {time} · {event}: {winner} won · {n} more", after:"\"{event}: {winner} won\" [+n count]" },
  { surface:"Home", file:"src/features/home/guestUpdates.js", before:"Correction · {event}", after:"\"{event} corrected\"" },
  { surface:"Duels", file:"src/features/duels/duelView.js", before:"Open to anyone · {n} min / Waiting for {name} to accept · {n} min / Open challenge · {n} min", after:"\"Open to anyone\" / \"Waiting for {name} to accept\" / \"Open challenge\" (no countdown)" },
  { surface:"Home", file:"src/features/home/HomeDuels.jsx", before:"{stake} · {n} min", after:"\"{stake}\"" },
  { surface:"Duels", file:"src/features/duels/QuickDraw.jsx", before:"{status} · {n} min", after:"\"{status}\"" },
  { surface:"Duels", file:"src/features/duels/QuickDraw.jsx", before:"Tap when the screen flashes. Fastest tap wins. Tapping early is a foul. (on the offer screen, repeated on the play screen)", after:null },
  { surface:"Duels", file:"src/features/duels/QuickDraw.jsx", before:"This challenge lapsed. No chips move.", after:"\"Lapsed\"" },
  { surface:"Duels", file:"src/features/duels/QuickDraw.jsx", before:"Withdrawn. No chips move. / Declined. No chips move. / Voided by the commissioner. No chips move.", after:"\"Withdrawn\" / \"Declined\" / \"Voided by the commissioner\"" },
  { surface:"Duels", file:"src/features/duels/QuickDraw.jsx", before:"Rematch · {stake}", after:"\"Rematch for {stake}\"" },
  { surface:"Duels", file:"src/features/profile/PlayerSheet.jsx", before:"Once accepted, each of you plays on your own phone.", after:null },
  { surface:"Duels", file:"src/features/profile/PlayerSheet.jsx", before:"{won} won · {lost} lost", after:"\"{won}-{lost}\"" },
  { surface:"Draft", file:"src/features/draft/DraftSheet.jsx", before:"Pick order reverses each round.", after:"[the upcoming pick queue shows the snake]" },
  { surface:"Home", file:"src/features/draft/DraftSheet.jsx", before:"Pick {n} · {captain}", after:"\"{captain}'s pick\" [captain's chip]" },
  { surface:"Home", file:"src/features/draft/DraftSheet.jsx", before:"Waiting for teams to be confirmed", after:null },
  { surface:"Draft", file:"src/features/draft/DraftSheet.jsx", before:"Confirm the teams to reveal the draw. / Waiting for the commissioner to confirm.", after:"[Confirm teams button]" },
  { surface:"Draft", file:"src/features/draft/DraftSheet.jsx", before:"Your role · {role}", after:"[\"Your role\" label, {role} as its own value]" },
  { surface:"Home", file:"src/features/mvp/MvpHome.jsx", before:"The MVP gets 100 chips. Most votes wins; a tie is drawn.", after:"\"MVP +100\"" },
  { surface:"Home", file:"src/features/mvp/MvpHome.jsx", before:"Team MVP · {event}", after:"\"{event} MVP\"" },
  { surface:"Home", file:"src/features/mvp/MvpHome.jsx", before:"{event} · {n} s (vote sheet subtitle)", after:"\"{n} s\"" },
  { surface:"Awards", file:"src/features/awards/AwardsHome.jsx", before:"Votes can change until voting closes.", after:null },
  { surface:"Awards", file:"src/features/awards/AwardsHome.jsx", before:"{award} · Tie", after:"\"{award}\" [both winners' chips and names]" },
  { surface:"Commissioner", file:"src/features/awards/AwardsDesk.jsx", before:"Counted from team MVPs when voting closes.", after:"\"Counted from team MVPs\"" },
  { surface:"Commissioner", file:"src/features/awards/AwardsDesk.jsx", before:"of {n} voted · voting closed", after:"\"of {n} voted\" [Reveal/Reopen controls show it closed]" },
  { surface:"Commissioner", file:"src/features/awards/AwardsDesk.jsx", before:"{winner} · {votes}", after:"[{winner} with the vote count as a bold number]" },
  { surface:"Where and When", file:"src/features/geo/GeoPlay.jsx", before:"{label} · {n}s (last ten seconds on the button)", after:"[{label} with the seconds as their own number]" },
  { surface:"Where and When", file:"src/features/geo/GeoPlay.jsx", before:"Time's up · guess saved", after:"\"Time's up\" [check mark]" },
  { surface:"Where and When", file:"src/features/geo/GeoPlay.jsx", before:"Tap the map to drop your pin", after:"\"Drop your pin\"" },
  { surface:"Where and When", file:"src/features/geo/GeoPlay.jsx", before:"Tap where it was taken / Drag the pin, or tap to move it", after:null },
  { surface:"Where and When", file:"src/features/geo/GeoPlay.jsx", before:"Saved: your pin · {date}. Waiting for the reveal. / Waiting for the reveal.", after:null },
  { surface:"Where and When", file:"src/features/geo/GeoPlay.jsx", before:"Your guess saves as you go. / Changes save until the reveal.", after:null },
  { surface:"Where and When", file:"src/features/geo/GeoPlay.jsx", before:"No guess this photo.", after:"\"No guess\"" },
  { surface:"Where and When", file:"src/features/geo/GeoPlay.jsx", before:"{points} total · {place} of {n}", after:"[{points} and {place} as two numbers]" },
  { surface:"Home", file:"src/features/geo/GeoPlay.jsx", before:"Where and When · Photo {n} of {total}", after:"\"Where and When\"" },
  { surface:"Where and When", file:"src/features/geo/geoModel.js", before:"{date} · {hour}", after:"\"{date}, {hour}\"" },
  { surface:"Commissioner", file:"src/features/geo/GeoDesk.jsx", before:"placeholder: Shown at the reveal (Place, Caption)", after:"Caption placeholder \"Optional\"" },
  { surface:"Commissioner", file:"src/features/geo/GeoDesk.jsx", before:"Caption · optional", after:"\"Caption\"" },
  { surface:"Commissioner", file:"src/features/geo/GeoDesk.jsx", before:"Game running · photo {n} of {total}", after:"\"Photo {n} of {total} live\"" },
  { surface:"Profile", file:"src/features/music/WinSongPicker.jsx", before:"{artist} · {length}", after:"\"{artist}\"" },
  { surface:"Profile", file:"src/features/music/WinSongPicker.jsx", before:"Plays in the room when you win. A team plays its MVP's song; a duo, one partner's.", after:null },
  { surface:"Profile", file:"src/features/music/SnippetPreview.jsx", before:"Album version from YouTube", after:"[YouTube's own player]" },
  { surface:"Profile", file:"src/features/profile/ProfileEditor.jsx", before:"Chips are locked for the weekend.", after:"\"Locked\"" },
  { surface:"Profile", file:"src/features/alerts/Alerts.jsx", before:"Your match, your pick, a challenge", after:null },
  { surface:"Profile", file:"src/features/profile/TripDetails.jsx", before:"Food or drink needs · optional", after:"\"Food or drink needs\"" },
  { surface:"Profile", file:"src/features/profile/PlayerPass.jsx", before:"{event} · {round} (head-to-head rows)", after:"\"{event}\"" },
  { surface:"Check-in", file:"src/features/check-in/Onboarding.jsx", before:"Private. Only used to balance teams.", after:"\"Private\"" },
  { surface:"Check-in", file:"src/features/check-in/Onboarding.jsx", before:"Open it from your home screen to check in.", after:"[the install hint's drawn steps]" },
  { surface:"Results", file:"src/features/results/resultMoment.js", before:"{winner} won · {round}", after:"\"{winner} won {round}\"" },
  { surface:"Results", file:"src/features/results/lastCard.js", before:"Best bet · {pick}, {event}", after:"\"Best bet on {pick}\"" },
  { surface:"Results", file:"src/features/results/lastCard.js", before:"Bets / Quick Draw: {won}–{lost} · {net}", after:"\"Bets {won}–{lost}\" / \"Quick Draw {won}–{lost}\" with {net} as the value" },
  { surface:"Results", file:"src/features/results/lastCard.js", before:"High · {weekday} {time}", after:"\"High\"" },
  { surface:"Results", file:"src/features/results/LastCard.jsx, SavePoster.jsx", before:"Press and hold the image to save it.", after:"\"Press and hold to save\"" },
  { surface:"TV", file:"src/features/tv/TVCeremony.jsx", before:"{name} · {name} (draw crew)", after:"\"{name}, {name}\"" },
  { surface:"TV", file:"src/features/tv/TVCeremony.jsx", before:"Betting open · Winner pays 1:1", after:"[\"Betting open\" and \"Winner pays 1:1\" as two spaced units]" },
  { surface:"TV", file:"src/features/tv/NowPlaying.jsx", before:"{song} · {artist}", after:"[song in bone, artist muted beside it]" },
  { surface:"TV", file:"src/features/tv/TVMode.jsx", before:"Reconnecting · last update {time}", after:"\"Reconnecting\" [hollow lamp]" },
  { surface:"TV", file:"src/features/tv/TVMode.jsx", before:"{round} · beat {name} · {next} next", after:"[round, beat {name}, {next} next as spaced units]" },
  { surface:"TV", file:"src/features/tv/TVMode.jsx", before:"Corrected · {what}", after:"[\"Corrected\" stamp, {what} beside it]" },
  { surface:"TV", file:"src/features/tv/TVPokerMoments.jsx", before:"Blinds up · small / big", after:"\"Blinds up\"" },
  { surface:"TV", file:"src/features/tv/TVDraft.jsx", before:"Available · {n}", after:"\"Available\" [{n} bold]" },
  { surface:"TV", file:"src/features/tv/TVPoker.jsx", before:"Out · {place}", after:"\"Out\" [{place} bold]" },
  { surface:"Poker", file:"src/features/poker/TableView.jsx", before:"Out · {place}", after:"\"Out\" [{place} bold]" },
  { surface:"Poker", file:"src/features/poker/TableView.jsx", before:"{clock} left in this level", after:"\"{clock} left\"" },
  { surface:"TV", file:"src/features/tv/tvModel.js", before:"Crew: {name}, {role} · {name}, {role}", after:"\"{name} ({role}), {name} ({role})\"" },
  { surface:"TV", file:"src/features/tv/SoundUnlockChip.jsx", before:"The TV is muted (under Click for sound)", after:null },
  { surface:"TV", file:"src/features/tv/TVGeo.jsx", before:"No guesses this photo", after:"\"No guesses\"" },
  { surface:"Commissioner", file:"src/features/director/directorPill.js", before:"{champion} · {chips} chips", after:"\"{champion} with {chips}\"" },
  { surface:"Commissioner", file:"src/features/director/directorPill.js", before:"Crew: {name} · {role}", after:"\"Crew: {name} ({role})\"" },
  { surface:"Commissioner", file:"src/features/director/directorPill.js", before:"{n} bets in · open {m} min", after:"\"{n} bets in\"" },
  { surface:"Commissioner", file:"src/features/director/directorPill.js", before:"{n} of {m} locked in · {k} still guessing", after:"\"{n} of {m} locked in\"" },
  { surface:"Commissioner", file:"src/features/director/runOfShow.js", before:"{event} · {n} photos", after:"\"{event}\"" },
  { surface:"Commissioner", file:"src/features/director/FinaleSheets.jsx", before:"{n} seats · {chips} chips", after:"\"{chips} chips\" [one row per seat]" },
  { surface:"Toasts", file:"src/App.jsx", before:"Your pick · {event}", after:"\"Your pick\" [Open draft]" },
  { surface:"Toasts", file:"src/App.jsx", before:"{captain} picked you · {event}", after:"\"{captain} picked you for {event}\"" },
  { surface:"Toasts", file:"src/App.jsx", before:"Quick Draw: {name} challenged you · {stake}", after:"\"{name} challenged you for {stake}\"" },
  { surface:"Toasts", file:"src/App.jsx", before:"{name}: open Quick Draw · {stake}", after:"\"{name} challenged anyone for {stake}\"" },
  { surface:"Toasts", file:"src/App.jsx", before:"{name} didn't answer · {stake} back / No one took your open challenge · {stake} back", after:"\"{name} didn't answer\" / \"No one took your challenge\"" },
  { surface:"Toasts", file:"src/App.jsx", before:"Quick Draw: {name} accepted / Quick Draw: {name} declined", after:"\"{name} accepted\" / \"{name} declined\" [their chip]" },
  { surface:"Toasts", file:"src/App.jsx", before:"Result cleared. Betting stays closed.", after:"\"Result cleared\"" },
  { surface:"Toasts", file:"src/App.jsx", before:"{event} posted, wagers settled", after:"\"{event} posted\"" },
  { surface:"Toasts", file:"src/App.jsx", before:"{event} shelved · {n} bets returned", after:"\"{event} shelved. {n} bets returned\"" },
  { surface:"Toasts", file:"src/App.jsx", before:"This phone was signed out of commissioner mode.", after:"\"Signed out of commissioner mode\"" },
  { surface:"Home", file:"src/features/moments/SkyStrip.jsx", before:"{event} · {winner}", after:"[{event} with the winner's name in bold]" },
  { surface:"Results", file:"src/features/moments/PhoneMoments.jsx", before:"MVP · {event}", after:"\"{event} MVP\"" },
  { surface:"Commissioner", file:"src/App.jsx", before:"Crew: {name} ({role}) · {name} ({role}) (announce sheet)", after:"\"Crew: {name} ({role}), {name} ({role})\"" },
  { surface:"Commissioner", file:"src/App.jsx", before:"Official result · revision {n}", after:"\"Official result\"" },
  { surface:"Commissioner", file:"src/features/awards/awardsModel.js", before:"Superlatives, voted on every phone (menu note)", after:null },
  { surface:"Commissioner", file:"shared/geo.js", before:"{event} · {n} photos (Start game)", after:"\"{event}\"" },
  { surface:"Commissioner", file:"shared/show.js", before:"{event} · {n} of {m} voted (Close MVP vote)", after:"\"{n} of {m} voted\"" },
  { surface:"Commissioner", file:"shared/show.js", before:"{award} · {n} of {m} (Next award)", after:"\"{award} ({n} of {m})\"" },
  { surface:"Poker", file:"src/App.jsx", before:"Not seated · your {chips} chips carry", after:"[\"Not seated\" with {chips} as the number beside it]" },
  { surface:"Poker", file:"src/App.jsx", before:"Away · carries {chips}", after:"[\"Away\" with {chips} beside it]" },
  { surface:"Events", file:"src/features/weekend/Schedule.jsx", before:"October 30 to November 1, 2026 (under the Events heading)", after:null },
  { surface:"Events", file:"src/features/weekend/Schedule.jsx", before:"{n} of {total} complete", after:"[a lamp per row: steady live, flashing next, unlit done, struck shelved]" },
  { surface:"Events", file:"src/features/weekend/Schedule.jsx", before:"800 CHIPS / 1200 CHIPS / POKER (session tag)", after:"[PayoutLadder: 1st medallion and amount on each row]" },
  { surface:"Events", file:"src/features/weekend/Schedule.jsx", before:"Won by {names}", after:"[winners' photo chips; your place as a medallion]" },
  { surface:"Events", file:"src/features/weekend/Schedule.jsx", before:"Event crew {name} {role} (under each row)", after:"[your own crew role only, as your chip and the role]" },
  { surface:"Events", file:"src/features/weekend/Schedule.jsx", before:"COMPLETE (status under a posted event)", after:"[unlit lamp]" },
  { surface:"Events", file:"src/features/weekend/Schedule.jsx", before:"{n} played (folded session)", after:"[the session's winners as photo chips]" },
  { surface:"Events", file:"src/features/weekend/Schedule.jsx", before:"+ Add an event", after:"\"Add event\" [plus icon]" },
  { surface:"Event sheet", file:"src/App.jsx EventSheet", before:"{Session} · {Individual | Pairs | Teams} (sheet subtitle)", after:null },
  { surface:"Event sheet", file:"src/App.jsx EventSheet", before:"Event info (disclosure) with the event description and \"{n} chips to win\"", after:"[before: who's playing as photo chips, GameSteps drawn steps, PayoutLadder]" },
  { surface:"Event sheet", file:"src/App.jsx EventSheet", before:"1st: {names} +{n} each / 2nd: ... / Crew: {names} +{n} each", after:"[podium: a medallion per place, photo chips with names, the amount]" },
  { surface:"Event sheet", file:"src/App.jsx EventSheet", before:"Corrected · {reason} · {n} bets voided", after:"\"Corrected: {reason}\"" },
  { surface:"Event sheet", file:"src/features/weekend/ContestPanel.jsx", before:"You're playing · Your bet {n}", after:"\"You're playing\" [your bet as a drawn chip and amount]" },
  { surface:"Event sheet", file:"src/features/weekend/EventSheetParts.jsx", before:"(new) what is riding", after:"[chip, amount, \"In play\", bettors' photo chips]" },
  { surface:"Event sheet", file:"src/features/weekend/EventSheetParts.jsx", before:"(new) your chips from a posted event", after:"[your chip, \"You\", the signed amount in green or clay]" },
  { surface:"Commissioner", file:"src/App.jsx EventSheet", before:"Format: {4 teams of 3}, fits {12}. Exact fit. / Assign {n} to event crew. / {n} short.", after:"\"{4 teams of 3}\" [count button \"{12} / {12}\", clay when it does not fit; the server's fit error when it fails]" },
  { surface:"Commissioner", file:"src/App.jsx EventSheet", before:"Teams stay hidden until this event is announced.", after:null },
  { surface:"Commissioner", file:"src/App.jsx EventSheet", before:"Crew do not compete and earn the 3rd-place award, +{n}. / Crew do not compete or score.", after:"\"Crew\" [+{n} in amber]" },
  { surface:"Commissioner", file:"src/App.jsx EventSheet", before:"Bets on the team stay. Outright bets on the player leaving are voided.", after:"\"Voids bets on the player leaving.\"" },
  { surface:"Commissioner", file:"src/App.jsx EventSheet", before:"Worth. Clear the result to change it", after:"\"Worth\" [disabled values]" },
  { surface:"Commissioner", file:"src/App.jsx EventSheet", before:"How it works / When (edit labels)", after:"\"How to play\" / \"Session\"" },
  { surface:"Commissioner", file:"src/App.jsx EventSheet", before:"More options", after:"\"More\"" },
  { surface:"Commissioner", file:"src/App.jsx EventSheet", before:"Next: {blocker}", after:"\"{blocker}\"" },
  { surface:"Commissioner", file:"src/features/weekend/ContestPanel.jsx", before:"Tap 1st, 2nd and 3rd.", after:"[each pick shows the place it takes; the button reads \"Pick 2nd\" until the order is complete]" },
  { surface:"Commissioner", file:"src/features/weekend/ContestPanel.jsx", before:"Choose {n} more to advance.", after:"[the button reads \"Pick {n} more\" until enough are chosen]" },
  { surface:"Commissioner", file:"src/features/weekend/ContestPanel.jsx", before:"Reorder once the chips on this match come off.", after:"\"Chips are on this match.\"" },
  { surface:"Home", file:"src/features/home/GuestHome.jsx", before:"{session} (Friday Night etc. beside First event, and under each Coming up row)", after:null },
  { surface:"Home", file:"src/features/home/GuestHome.jsx", before:"You are marked away", after:"\"Marked away\"" },
  { surface:"Standings", file:"src/features/standings/Standings.jsx", before:"{session} (Next event card)", after:null },
];
