/* The built-in Trivia bank. Worker only: nothing under src/ or shared/
   imports this file (tests/trivia.test.mjs scans for it), so no right
   answer ships in a client bundle. The commissioner's desk reads it over
   GET /api/trivia/bank with the commissioner token; a game copies the
   questions it plays into state.trivia at its start, and every frame
   projects them (shared/trivia.js projectTrivia).

   The right answer is always written first; a game deals the four options
   in a fresh order. Facts are stable ones (no "current champion"), and a
   closest-number answer is one unambiguous whole number with its unit.
   A tune names the recording the TV plays (its first option) and three
   decoys from the same years and sound. */

const c = (id, text, options) => ({ id, format:"choice", text, options, answer:0 });
const n = (id, text, answer, unit, digits = null) => ({ id, format:"number", text, answer, unit,
  ...(digits ? { digits } : {}) });
const song = (title, artist) => ({ title, artist });
const t = (id, answer, ...decoys) => ({ id, format:"tune", text:"", options:[answer, ...decoys], answer:0 });

export const TRIVIA_BANK = Object.freeze([
  { id:"sports", name:"Sports", questions:[
    c("sports-01", "The Fosbury Flop is a technique in which event?", ["High jump", "Pole vault", "Diving", "Long jump"]),
    c("sports-02", "Which country hosted the first FIFA World Cup, in 1930?", ["Uruguay", "Brazil", "Italy", "Argentina"]),
    c("sports-03", "Who holds MLB's career home run record?", ["Barry Bonds", "Hank Aaron", "Babe Ruth", "Alex Rodriguez"]),
    c("sports-04", "Which golfer has won the most men's major championships?", ["Jack Nicklaus", "Tiger Woods", "Arnold Palmer", "Ben Hogan"]),
    c("sports-05", "Which team finished an NFL season undefeated, Super Bowl included?",
      ["1972 Miami Dolphins", "2007 New England Patriots", "1985 Chicago Bears", "1989 San Francisco 49ers"]),
    c("sports-06", "Which tennis major is played on grass?", ["Wimbledon", "US Open", "French Open", "Australian Open"]),
    c("sports-07", "Who is the NBA's all-time leading scorer?", ["LeBron James", "Kareem Abdul-Jabbar", "Karl Malone", "Kobe Bryant"]),
    c("sports-08", "Who has won the most Olympic gold medals?", ["Michael Phelps", "Usain Bolt", "Carl Lewis", "Mark Spitz"]),
    c("sports-09", "What is the NHL's playoff championship trophy?", ["Stanley Cup", "Conn Smythe Trophy", "Hart Trophy", "Vezina Trophy"]),
    n("sports-10", "What is a perfect score in ten-pin bowling?", 300, "points"),
    n("sports-11", "How long is an American football field, end zones included?", 120, "yards"),
    n("sports-12", "How wide is an NBA rim, across?", 18, "inches"),
    n("sports-13", "In what year was Super Bowl I played?", 1967, ""),
    n("sports-14", "What number did Wayne Gretzky wear?", 99, ""),
  ] },
  { id:"screen", name:"Movies and TV", questions:[
    c("screen-01", "In Breaking Bad, what name does Walter White go by?", ["Heisenberg", "Oppenheimer", "Einstein", "Feynman"]),
    c("screen-02", "Which movie has the line \"I'll be back\"?", ["The Terminator", "Predator", "Total Recall", "Commando"]),
    c("screen-03", "What is the paper company in The Office?", ["Dunder Mifflin", "Initech", "Vandelay Industries", "Sterling Cooper"]),
    c("screen-04", "Who directed Jaws, E.T. and Jurassic Park?", ["Steven Spielberg", "George Lucas", "James Cameron", "Ridley Scott"]),
    c("screen-05", "What is the coffee shop in Friends called?", ["Central Perk", "Monk's Café", "The Max", "MacLaren's"]),
    c("screen-06", "Which city does Ron Burgundy read the news in?", ["San Diego", "Los Angeles", "San Francisco", "Sacramento"]),
    c("screen-07", "What do Dale and Brennan name their company in Step Brothers?",
      ["Prestige Worldwide", "Catalina Entertainment", "Dragon Enterprises", "Big Kahuna Events"]),
    c("screen-08", "Which town is Stranger Things set in?", ["Hawkins", "Derry", "Twin Peaks", "Sunnydale"]),
    c("screen-09", "What is Kramer's first name in Seinfeld?", ["Cosmo", "Kenny", "Jerome", "Newman"]),
    c("screen-10", "Who played the Joker in The Dark Knight?", ["Heath Ledger", "Jared Leto", "Joaquin Phoenix", "Jack Nicholson"]),
    c("screen-11", "Which film won the first Academy Award for Best Picture?", ["Wings", "Sunrise", "The Jazz Singer", "Metropolis"]),
    n("screen-12", "In what year was the first Toy Story released?", 1995, ""),
    n("screen-13", "In what year was Superbad released?", 2007, ""),
    n("screen-14", "How many seasons did the American Office run?", 9, "seasons"),
  ] },
  { id:"music", name:"Music", questions:[
    c("music-01", "Chris Martin is the lead singer of which band?", ["Coldplay", "Keane", "Snow Patrol", "The Fray"]),
    c("music-02", "What was Elvis Presley's home called?", ["Graceland", "Neverland", "Paisley Park", "Sun Studio"]),
    c("music-03", "Who released the album Thriller?", ["Michael Jackson", "Prince", "Lionel Richie", "Stevie Wonder"]),
    c("music-04", "Which rapper was born Aubrey Graham?", ["Drake", "J. Cole", "The Weeknd", "Future"]),
    c("music-05", "Which band recorded Hotel California?", ["Eagles", "Fleetwood Mac", "The Doobie Brothers", "Steely Dan"]),
    c("music-06", "Which Taylor Swift album has Shake It Off on it?", ["1989", "Red", "Reputation", "Fearless"]),
    c("music-07", "What does Travis Barker play?", ["Drums", "Bass", "Guitar", "Keyboards"]),
    c("music-08", "Which singer is called The Boss?", ["Bruce Springsteen", "Bob Seger", "Tom Petty", "Billy Joel"]),
    c("music-09", "What was Kanye West's first album?", ["The College Dropout", "Late Registration", "Graduation", "808s & Heartbreak"]),
    c("music-10", "What is Eminem's alter ego?", ["Slim Shady", "Marshall Law", "Dr. Detroit", "Stan"]),
    c("music-11", "Who was the lead singer of Queen?", ["Freddie Mercury", "Brian May", "Roger Daltrey", "Robert Plant"]),
    n("music-12", "In what year did Nirvana release Nevermind?", 1991, ""),
    n("music-13", "In what year did the Beatles first play The Ed Sullivan Show?", 1964, ""),
    n("music-14", "How many keys are on a standard piano?", 88, "keys"),
  ] },
  { id:"food", name:"Food and Drink", questions:[
    c("food-01", "Which country does Gouda cheese come from?", ["Netherlands", "Switzerland", "Belgium", "Denmark"]),
    c("food-02", "Which spirit goes in a classic margarita?", ["Tequila", "Rum", "Vodka", "Gin"]),
    c("food-03", "Which beer calls itself the King of Beers?", ["Budweiser", "Miller High Life", "Coors Banquet", "Pabst Blue Ribbon"]),
    c("food-04", "Marzipan is made mostly from which nut?", ["Almond", "Hazelnut", "Pistachio", "Cashew"]),
    c("food-05", "Sake is brewed from what?", ["Rice", "Barley", "Plums", "Potatoes"]),
    c("food-06", "Which pasta is named for looking like little ears?", ["Orecchiette", "Farfalle", "Conchiglie", "Fusilli"]),
    c("food-07", "In which country was the Caesar salad invented?", ["Mexico", "Italy", "United States", "Spain"]),
    c("food-08", "Which country grows the most coffee?", ["Brazil", "Colombia", "Vietnam", "Ethiopia"]),
    c("food-09", "What is the main ingredient in hummus?", ["Chickpeas", "Lentils", "White beans", "Fava beans"]),
    c("food-10", "Which spirit is in a Moscow Mule?", ["Vodka", "Gin", "Whiskey", "Rum"]),
    c("food-11", "Tabasco sauce is made in which state?", ["Louisiana", "Texas", "New Mexico", "Mississippi"]),
    n("food-12", "In what year was Coca-Cola invented?", 1886, ""),
    n("food-13", "How many calories are in a 12-ounce can of Coca-Cola?", 140, "calories"),
    n("food-14", "How many beers are in a standard case?", 24, "beers"),
  ] },
  { id:"geography", name:"Geography", questions:[
    c("geography-01", "What is the capital of Australia?", ["Canberra", "Sydney", "Melbourne", "Perth"]),
    c("geography-02", "What is the smallest US state by area?", ["Rhode Island", "Delaware", "Connecticut", "New Jersey"]),
    c("geography-03", "Which US state has the most coastline?", ["Alaska", "Florida", "California", "Hawaii"]),
    c("geography-04", "What is the capital of Canada?", ["Ottawa", "Toronto", "Montreal", "Vancouver"]),
    c("geography-05", "Mount Kilimanjaro is in which country?", ["Tanzania", "Kenya", "Uganda", "Ethiopia"]),
    c("geography-06", "Which of these states does not border Arizona?", ["Texas", "Nevada", "Utah", "New Mexico"]),
    c("geography-07", "What is the largest hot desert in the world?", ["Sahara", "Gobi", "Kalahari", "Mojave"]),
    c("geography-08", "Which city is called the Big Easy?", ["New Orleans", "Memphis", "Nashville", "Atlanta"]),
    c("geography-09", "Machu Picchu is in which country?", ["Peru", "Bolivia", "Chile", "Ecuador"]),
    c("geography-10", "What is the capital of New Zealand?", ["Wellington", "Auckland", "Christchurch", "Queenstown"]),
    c("geography-11", "Which is the only one-syllable US state?", ["Maine", "Utah", "Ohio", "Iowa"]),
    n("geography-12", "How many countries are in Africa?", 54, "countries"),
    n("geography-13", "How tall is Mount Everest?", 29032, "feet"),
    n("geography-14", "How many US states border Canada?", 13, "states"),
  ] },
  { id:"science", name:"Science", questions:[
    c("science-01", "Which element has the symbol Au?", ["Gold", "Silver", "Argon", "Aluminum"]),
    c("science-02", "Which planet is called the Red Planet?", ["Mars", "Jupiter", "Venus", "Mercury"]),
    c("science-03", "What is the hardest natural substance?", ["Diamond", "Quartz", "Titanium", "Granite"]),
    c("science-04", "Which gas do plants take in from the air?", ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"]),
    c("science-05", "What is the largest organ of the human body?", ["Skin", "Liver", "Lungs", "Brain"]),
    c("science-06", "Which star is closest to Earth?", ["The Sun", "Proxima Centauri", "Sirius", "Alpha Centauri A"]),
    c("science-07", "Which blood type can be given to anyone?", ["O negative", "O positive", "AB negative", "AB positive"]),
    c("science-08", "Which element has atomic number 1?", ["Hydrogen", "Helium", "Oxygen", "Carbon"]),
    c("science-09", "Which part of the cell is called its powerhouse?", ["Mitochondria", "Nucleus", "Ribosome", "Golgi body"]),
    c("science-10", "What does DNA stand for?", ["Deoxyribonucleic acid", "Dinucleic acid", "Deoxyribose nitrate", "Dual nucleic array"]),
    n("science-11", "How many bones are in an adult human body?", 206, "bones"),
    n("science-12", "How fast does light travel?", 186282, "miles a second"),
    n("science-13", "At what temperature does water boil at sea level?", 212, "°F"),
    n("science-14", "How many hearts does an octopus have?", 3, "hearts"),
  ] },
  { id:"internet", name:"2000s and 2010s", questions:[
    c("internet-01", "Which social network started in a Harvard dorm in 2004?", ["Facebook", "Myspace", "Friendster", "Twitter"]),
    c("internet-02", "What was PSY's 2012 hit?", ["Gangnam Style", "Gentleman", "Daddy", "Hangover"]),
    c("internet-03", "Which console did Nintendo release in 2006?", ["Wii", "GameCube", "Switch", "Wii U"]),
    c("internet-04", "Which 2013 dance craze was set to a Baauer song?", ["Harlem Shake", "Dougie", "Nae Nae", "Stanky Leg"]),
    c("internet-05", "The Ice Bucket Challenge raised money for which disease?", ["ALS", "Cancer", "Diabetes", "Parkinson's"]),
    c("internet-06", "Snooki and The Situation starred in which show?", ["Jersey Shore", "The Hills", "Laguna Beach", "Big Brother"]),
    c("internet-07", "Which game had everyone catching creatures outside in summer 2016?",
      ["Pokémon Go", "Ingress", "Angry Birds", "Clash of Clans"]),
    c("internet-08", "Who interrupted Taylor Swift at the 2009 VMAs?", ["Kanye West", "Jay-Z", "Lil Wayne", "Chris Brown"]),
    c("internet-09", "Who was everyone's first friend on Myspace?", ["Tom", "Mark", "Chris", "Steve"]),
    c("internet-10", "What was the best-selling home console of the 2000s?", ["PlayStation 2", "Wii", "Xbox 360", "GameCube"]),
    c("internet-11", "Which app's logo is a ghost?", ["Snapchat", "Vine", "Kik", "Tumblr"]),
    c("internet-12", "A coffee cup was left in a 2019 scene of which show?", ["Game of Thrones", "Westworld", "The Witcher", "Vikings"]),
    n("internet-13", "In what year did YouTube launch?", 2005, ""),
    n("internet-14", "How many characters fit in a tweet before 2017?", 140, "characters"),
    n("internet-15", "In what year did the first iPhone come out?", 2007, ""),
  ] },
  { id:"arizona", name:"Arizona", questions:[
    c("arizona-01", "What is the capital of Arizona?", ["Phoenix", "Tucson", "Scottsdale", "Flagstaff"]),
    c("arizona-02", "Which spring training league plays in Arizona?", ["Cactus League", "Grapefruit League", "Desert League", "Sun League"]),
    c("arizona-03", "Which architect built Taliesin West in Scottsdale?", ["Frank Lloyd Wright", "Le Corbusier", "Frank Gehry", "I. M. Pei"]),
    c("arizona-04", "Where in Arizona do clocks change for daylight saving time?", ["Navajo Nation", "Tucson", "Flagstaff", "Yuma"]),
    c("arizona-05", "Which Phoenix mountain is named for an animal it looks like?",
      ["Camelback Mountain", "Piestewa Peak", "Superstition Mountains", "South Mountain"]),
    c("arizona-06", "Which river carved the Grand Canyon?", ["Colorado River", "Gila River", "Salt River", "Rio Grande"]),
    c("arizona-07", "Which company runs Scottsdale's big January car auction?", ["Barrett-Jackson", "Mecum", "RM Sotheby's", "Bonhams"]),
    c("arizona-08", "Arizona State's main campus is in which city?", ["Tempe", "Mesa", "Phoenix", "Scottsdale"]),
    c("arizona-09", "The Cardinals moved to Arizona from which city?", ["St. Louis", "Chicago", "Kansas City", "Baltimore"]),
    c("arizona-10", "Which tournament's 16th hole is the loudest in golf?",
      ["WM Phoenix Open", "The Players Championship", "The Masters", "Memorial Tournament"]),
    c("arizona-11", "What is Arizona's state bird?", ["Cactus wren", "Roadrunner", "Gila woodpecker", "Mourning dove"]),
    n("arizona-12", "In what year did Arizona become a state?", 1912, ""),
    n("arizona-13", "In what year did the Diamondbacks win the World Series?", 2001, ""),
    n("arizona-14", "How long is the Grand Canyon?", 277, "miles"),
  ] },
  { id:"tunes-2000s", name:"Name that tune: 2000s", questions:[
    t("tunes-2000s-01", song("Mr. Brightside", "The Killers"), song("Take Me Out", "Franz Ferdinand"), song("Last Nite", "The Strokes"),
      song("The Middle", "Jimmy Eat World")),
    t("tunes-2000s-02", song("In Da Club", "50 Cent"), song("Hot in Herre", "Nelly"), song("Get Low", "Lil Jon & The East Side Boyz"),
      song("Lean Back", "Terror Squad")),
    t("tunes-2000s-03", song("Yeah!", "Usher"), song("Goodies", "Ciara"), song("Laffy Taffy", "D4L"), song("Promiscuous", "Nelly Furtado")),
    t("tunes-2000s-04", song("Hey Ya!", "OutKast"), song("Crazy", "Gnarls Barkley"), song("Float On", "Modest Mouse"),
      song("Feel Good Inc.", "Gorillaz")),
    t("tunes-2000s-05", song("Seven Nation Army", "The White Stripes"), song("Are You Gonna Be My Girl", "Jet"),
      song("Use Somebody", "Kings of Leon"), song("Hysteria", "Muse")),
    t("tunes-2000s-06", song("Gold Digger", "Kanye West"), song("Ridin'", "Chamillionaire"), song("Grillz", "Nelly"),
      song("Ms. New Booty", "Bubba Sparxxx")),
    t("tunes-2000s-07", song("Lose Yourself", "Eminem"), song("Hate It or Love It", "The Game"), song("Many Men", "50 Cent"),
      song("Numb / Encore", "Jay-Z & Linkin Park")),
    t("tunes-2000s-08", song("Toxic", "Britney Spears"), song("Since U Been Gone", "Kelly Clarkson"), song("Complicated", "Avril Lavigne"),
      song("Hollaback Girl", "Gwen Stefani")),
    t("tunes-2000s-09", song("I Gotta Feeling", "The Black Eyed Peas"), song("Just Dance", "Lady Gaga"), song("Fireflies", "Owl City"),
      song("Hey, Soul Sister", "Train")),
    t("tunes-2000s-10", song("Sugar, We're Goin Down", "Fall Out Boy"), song("Helena", "My Chemical Romance"),
      song("I Write Sins Not Tragedies", "Panic! at the Disco"), song("Ocean Avenue", "Yellowcard")),
    t("tunes-2000s-11", song("Crazy in Love", "Beyoncé"), song("Hips Don't Lie", "Shakira"), song("Umbrella", "Rihanna"),
      song("SexyBack", "Justin Timberlake")),
    t("tunes-2000s-12", song("Low", "Flo Rida"), song("Lollipop", "Lil Wayne"), song("Party Like a Rockstar", "Shop Boyz"),
      song("Crank That (Soulja Boy)", "Soulja Boy")),
  ] },
  { id:"tunes-2010s", name:"Name that tune: 2010s", questions:[
    t("tunes-2010s-01", song("Uptown Funk", "Mark Ronson"), song("Happy", "Pharrell Williams"),
      song("Can't Stop the Feeling!", "Justin Timberlake"), song("Get Lucky", "Daft Punk")),
    t("tunes-2010s-02", song("Party Rock Anthem", "LMFAO"), song("Turn Down for What", "DJ Snake & Lil Jon"), song("Gangnam Style", "PSY"),
      song("We Found Love", "Rihanna")),
    t("tunes-2010s-03", song("Somebody That I Used to Know", "Gotye"), song("Pumped Up Kicks", "Foster the People"),
      song("Ho Hey", "The Lumineers"), song("Riptide", "Vance Joy")),
    t("tunes-2010s-04", song("Call Me Maybe", "Carly Rae Jepsen"), song("Starships", "Nicki Minaj"), song("Teenage Dream", "Katy Perry"),
      song("We Are Never Ever Getting Back Together", "Taylor Swift")),
    t("tunes-2010s-05", song("Thrift Shop", "Macklemore & Ryan Lewis"), song("Talk Dirty", "Jason Derulo"), song("Timber", "Pitbull"),
      song("Fancy", "Iggy Azalea")),
    t("tunes-2010s-06", song("Hotline Bling", "Drake"), song("Work", "Rihanna"), song("Panda", "Desiigner"), song("Trap Queen", "Fetty Wap")),
    t("tunes-2010s-07", song("SICKO MODE", "Travis Scott"), song("God's Plan", "Drake"), song("rockstar", "Post Malone"),
      song("XO Tour Llif3", "Lil Uzi Vert")),
    t("tunes-2010s-08", song("Old Town Road", "Lil Nas X"), song("Truth Hurts", "Lizzo"), song("Sunflower", "Post Malone & Swae Lee"),
      song("bad guy", "Billie Eilish")),
    t("tunes-2010s-09", song("Shut Up and Dance", "Walk the Moon"), song("Pompeii", "Bastille"), song("Take Me to Church", "Hozier"),
      song("Stressed Out", "Twenty One Pilots")),
    t("tunes-2010s-10", song("Rolling in the Deep", "Adele"), song("Royals", "Lorde"), song("Stay with Me", "Sam Smith"),
      song("Love Yourself", "Justin Bieber")),
    t("tunes-2010s-11", song("HUMBLE.", "Kendrick Lamar"), song("Bodak Yellow", "Cardi B"), song("Mask Off", "Future"),
      song("Congratulations", "Post Malone")),
    t("tunes-2010s-12", song("Blinding Lights", "The Weeknd"), song("Don't Start Now", "Dua Lipa"), song("Watermelon Sugar", "Harry Styles"),
      song("Levitating", "Dua Lipa")),
  ] },
  { id:"tunes-anthems", name:"Name that tune: anthems", questions:[
    t("tunes-anthems-01", song("September", "Earth, Wind & Fire"), song("Le Freak", "Chic"), song("Celebration", "Kool & The Gang"),
      song("I Will Survive", "Gloria Gaynor")),
    t("tunes-anthems-02", song("Don't Stop Believin'", "Journey"), song("Jessie's Girl", "Rick Springfield"), song("Eye of the Tiger", "Survivor"),
      song("Take On Me", "a-ha")),
    t("tunes-anthems-03", song("Livin' on a Prayer", "Bon Jovi"), song("Pour Some Sugar on Me", "Def Leppard"),
      song("Here I Go Again", "Whitesnake"), song("Summer of '69", "Bryan Adams")),
    t("tunes-anthems-04", song("Sweet Caroline", "Neil Diamond"), song("Brown Eyed Girl", "Van Morrison"), song("Piano Man", "Billy Joel"),
      song("American Pie", "Don McLean")),
    t("tunes-anthems-05", song("Wonderwall", "Oasis"), song("Bitter Sweet Symphony", "The Verve"), song("Song 2", "Blur"),
      song("Creep", "Radiohead")),
    t("tunes-anthems-06", song("All Star", "Smash Mouth"), song("Steal My Sunshine", "Len"), song("Flagpole Sitta", "Harvey Danger"),
      song("Closing Time", "Semisonic")),
    t("tunes-anthems-07", song("Africa", "Toto"), song("Don't You (Forget About Me)", "Simple Minds"),
      song("Everybody Wants to Rule the World", "Tears for Fears"), song("Down Under", "Men at Work")),
    t("tunes-anthems-08", song("Hypnotize", "The Notorious B.I.G."), song("California Love", "2Pac"), song("Gin and Juice", "Snoop Dogg"),
      song("Regulate", "Warren G")),
    t("tunes-anthems-09", song("Still D.R.E.", "Dr. Dre"), song("Big Pimpin'", "Jay-Z"), song("Ruff Ryders' Anthem", "DMX"),
      song("Got Your Money", "Ol' Dirty Bastard")),
    t("tunes-anthems-10", song("Smells Like Teen Spirit", "Nirvana"), song("Black Hole Sun", "Soundgarden"), song("Plush", "Stone Temple Pilots"),
      song("Alive", "Pearl Jam")),
    t("tunes-anthems-11", song("No Diggity", "Blackstreet"), song("Waterfalls", "TLC"), song("This Is How We Do It", "Montell Jordan"),
      song("Motownphilly", "Boyz II Men")),
    t("tunes-anthems-12", song("Semi-Charmed Life", "Third Eye Blind"), song("Mr. Jones", "Counting Crows"), song("Name", "Goo Goo Dolls"),
      song("3AM", "Matchbox Twenty")),
  ] },
].map(category => Object.freeze({ ...category, questions:Object.freeze(category.questions.map(Object.freeze)) })));

export const bankCategory = id => TRIVIA_BANK.find(category => category.id === id) || null;
export const bankQuestion = (categoryId, questionId) => bankCategory(categoryId)?.questions.find(q => q.id === questionId) || null;
